<!-- Welcome to numpy tutorial -->

# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,98,8]], np.int32)

In [3]:
myarr

array([[ 3,  6, 98,  8]])

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1] = 45

In [8]:
myarr

array([[ 3, 45, 98,  8]])

# Array creation: Conversion from other Python structures

In [9]:
listarray = np.array([[1,2,3], [5,4,6], [5,4,7]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 4, 6],
       [5, 4, 7]])

In [12]:
listarray.dtype, listarray.shape, listarray.size

(dtype('int32'), (3, 3), 9)

In [13]:
np.array({34,65,48})

array({48, 65, 34}, dtype=object)

In [14]:
zeros = np.zeros((2, 5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1, 5, 4) #(start, last, size)

In [19]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.60219035e-306, 4.45061456e-308, 1.02360867e-306],
       [1.42417900e-306, 1.78019082e-306, 1.37961913e-306,
        6.23057349e-307, 1.02360935e-306, 1.69120416e-306],
       [1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        1.33508761e-307, 6.23037657e-307, 6.23053954e-307],
       [1.78020169e-306, 1.78021527e-306, 2.22523004e-306,
        8.45592576e-307, 8.34445562e-308, 3.91792476e-317]])

In [22]:
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr = arr.reshape(3, 33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr = arr.ravel() # It convert it to 1D array

In [32]:
arr.shape

(99,)

In [33]:
# Axis
x = [[1,2,3], [4,5,6], [7,8,9]] 

In [34]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ar.sum(axis = 0), ar.sum(axis = 1)
#axis = 0 for rows , axis = 1 for column

(array([12, 15, 18]), array([ 6, 15, 24]))