<!-- Welcome to numpy tutorial -->

# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,98,8]], np.int32)

In [3]:
myarr

array([[ 3,  6, 98,  8]])

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1] = 45

In [8]:
myarr

array([[ 3, 45, 98,  8]])

# Array creation: Conversion from other Python structures

In [9]:
listarray = np.array([[1,2,3], [5,4,6], [5,4,7]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 4, 6],
       [5, 4, 7]])

In [11]:
listarray.dtype, listarray.shape, listarray.size

(dtype('int32'), (3, 3), 9)

In [12]:
np.array({34,65,48})

array({48, 65, 34}, dtype=object)

In [13]:
zeros = np.zeros((2, 5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1, 5, 4) #(start, last, size)

In [18]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [19]:
emp = np.empty((4,6))

In [20]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.60219035e-306, 4.45061456e-308, 1.02360867e-306],
       [1.42417900e-306, 1.78019082e-306, 1.37961913e-306,
        6.23057349e-307, 1.02360935e-306, 1.69120416e-306],
       [1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        1.33508761e-307, 6.23037657e-307, 6.23053954e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        1.86921143e-306, 6.23061763e-307, 2.07958987e-312]])

In [21]:
emp_like = np.empty_like(lspace)

In [22]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr = arr.reshape(3, 33)

In [28]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr = arr.ravel() # It convert it to 1D array

In [30]:
arr.shape

(99,)

In [31]:
# Axis
x = [[1,2,3], [4,5,6], [7,8,9]] 

In [32]:
ar = np.array(x)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar.sum(axis = 0), ar.sum(axis = 1)
#axis = 0 for rows , axis = 1 for column

(array([12, 15, 18]), array([ 6, 15, 24]))

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
ar.flat

In [37]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [38]:
ar.ndim

2

In [39]:
ar.size

9

In [40]:
ar.nbytes

36

In [41]:
one = np.array([1,3,4,546,2])

In [42]:
one.argmax()

3

In [43]:
one.argmin()

0

In [44]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int32)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.argmin(), ar.argmax(), ar.argmax(axis = 0), ar.argmin(axis = 1), ar.argsort(axis = 0), ar.argsort(axis = 1)

(0,
 8,
 array([2, 2, 2], dtype=int32),
 array([0, 0, 0], dtype=int32),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]], dtype=int32),
 array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]], dtype=int32))

In [47]:
 ar.ravel(), ar.reshape([9,])

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [48]:
ar2 = np.array([[1,2,1], [4,0,6], [8,1,0]])

In [49]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [50]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [51]:
ar.sum(), ar.max(), ar.min()

(45, 9, 1)

In [52]:
np.where(ar>5), type(np.where(ar>5)) 

((array([1, 2, 2, 2], dtype=int32), array([2, 0, 1, 2], dtype=int32)), tuple)

In [53]:
import sys

In [54]:
py_ar = [0,4,55,2]

In [55]:
np_ar = np.array(py_ar)

In [56]:
sys.getsizeof(1) * len(py_ar)

56

In [57]:
np_ar.itemsize * np_ar.size

16